services:

  mysql:
    image: mysql:8.0
    container_name: eventhub-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: eventhub

    volumes:
      - mysql_data:/var/lib/mysql

    ports:
      - "3307:3306"

    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-uroot",
          "-p${DB_PASSWORD}"
        ]
      interval: 10s
      timeout: 5s
      retries: 10


  backend:
    build:
      context: .

    container_name: eventhub-backend
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      DB_HOST: mysql
      DB_NAME: eventhub
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "8080:8080"


  frontend:
    build:
      context: ../eventhub-frontend

    container_name: eventhub-frontend
    restart: unless-stopped

    depends_on:
      - backend

    ports:
      - "3000:80"


volumes:
  mysql_data: