spring.application.name=eventhub-backend

spring.datasource.url=jdbc:mysql://localhost:3306/eventhub
spring.datasource.username=root
spring.datasource.password=Pawan@7717

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080